"""Sync NexBase build status into the Obsidian vault.

Writes ONE file it owns:
    01-Projects/VISHVEX/NEXBASE-BUILD-STATUS.md

Every number is read from the live repo, so re-running refreshes rather than
restates. Nothing else in the vault is touched, and the file is only rewritten
when the content actually changed.

    python scripts/sync_vault.py            # write if changed
    python scripts/sync_vault.py --check    # report, write nothing
"""
from __future__ import annotations

import csv
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTE = Path("01-Projects/VISHVEX/NEXBASE-BUILD-STATUS.md")
MARKER = "<!-- generated by scripts/sync_vault.py - edits here are overwritten -->"


def vault_root() -> Path | None:
    """Read the vault path from Obsidian's own config."""
    cfg = Path(os.environ.get("APPDATA", "")) / "obsidian" / "obsidian.json"
    override = os.environ.get("OBSIDIAN_VAULT")
    if override:
        return Path(override)
    if not cfg.exists():
        return None
    try:
        vaults = json.loads(cfg.read_text(encoding="utf-8")).get("vaults", {})
    except (json.JSONDecodeError, OSError):
        return None
    open_vaults = [v["path"] for v in vaults.values() if v.get("open")] or [
        v["path"] for v in vaults.values()
    ]
    return Path(open_vaults[0]) if open_vaults else None


def test_count() -> str:
    try:
        out = subprocess.run(
            [sys.executable, "-m", "pytest", "--collect-only", "-q"],
            cwd=ROOT, capture_output=True, text=True, timeout=180,
        ).stdout
        match = re.search(r"(\d+)\s+tests? collected", out)
        if match:
            return match.group(1)
        # This pytest prints a per-file tally instead of a total.
        per_file = re.findall(r"^\S+\.py:\s*(\d+)$", out, flags=re.M)
        return str(sum(int(n) for n in per_file)) if per_file else "unknown"
    except Exception:
        return "unknown"


def facts() -> dict:
    sys.path.insert(0, str(ROOT))
    from nexbase.config import get_settings
    from nexbase.discovery import taxonomy
    from nexbase.discovery.registry import build_registry

    s = get_settings()
    industries = taxonomy.load_industries()
    terms = taxonomy.load_search_terms()

    schema_tables = len(re.findall(
        r"CREATE TABLE IF NOT EXISTS (\w+)",
        (ROOT / "nexbase" / "db" / "schema.sql").read_text(encoding="utf-8"),
    ))
    return {
        "tests": test_count(),
        "sources": [src.describe() for src in build_registry(s).sources()],
        "industries": len(industries),
        "core_subsectors": sum(1 for i in industries if i.is_core),
        "non_core_subsectors": sum(1 for i in industries if not i.is_core),
        "mfg_subsectors": sum(1 for i in industries if i.is_manufacturing),
        "search_terms": len(terms),
        "soc_codes": len({t.soc_code for t in terms}),
        "schema_tables": schema_tables,
        "size_band": f"{s.size_filter_min}-{s.size_filter_max}",
        "domain_resolver": s.domain_resolver_enabled,
        "size_resolver": s.size_resolver_enabled,
        "domain_cache_days": s.domain_cache_max_age_days,
        "domain_negative_cache_days": s.domain_negative_cache_days,
        "freshness": f"at most {s.freshness_max_days} days old",
        "max_title_variants": s.planner_max_title_variants,
        "source_max_calls": s.source_max_calls_per_run,
        "max_pages_per_query": s.discovery_max_pages_per_query,
        "max_results_per_query": s.discovery_max_results_per_query,
        "excluded_socs": sorted(taxonomy.EXCLUDED_SOC_MAJOR_GROUPS),
    }


def render(f: dict) -> str:
    def lst(items):
        return ", ".join(f"`{i}`" for i in items) if items else "_none_"

    def portals(source_class, enabled=True):
        return lst([x["portal"] for x in f["sources"]
                    if x["source_class"] == source_class and x["enabled"] is enabled])

    return f"""---
project: NexBase
client: Nex-Base
status: in development
scope: lead discovery + contact intelligence (outreach out of scope)
updated: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
---

# NexBase — Build Status

{MARKER}
Engineering status for the Nex-Base delivery, built to the Master Plan
(Phases 1-9). Requirements live in [[CLIENTS]]; commercial direction in
[[CURRENT-STATE]].

## Pipeline state

| Stage | State |
|---|---|
| Discovery (portals + ATS) | working |
| Normalization / dedup | working |
| Freshness (≤14d) | working |
| Qualification gate | working, evidence-limited |
| Contact discovery | working, variable yield |
| Enrichment waterfall | ZoomInfo primary, Apollo / Apify fallback: implemented, tested with mocks/fixtures, **live validation PENDING CLIENT CREDENTIALS**; Apify: **no enrichment actor confirmed** |
| Email verification | ZeroBounce wired after POC ranking, **off by default**; live validation pending |
| Export | CSV + `/leads` API |
| Outreach | **out of scope** — removed in Phase 1 |

## Sources (registry)

One handler per portal; `SOURCES_DISABLED` switches portals off.

- **DIRECT**: {portals("DIRECT")} (JobSpy handles indeed, linkedin; NexBase board
  adapters the rest)
- **ATS**: {portals("ATS")}
- **APIFY**: {portals("APIFY")}
- **Disabled**: {lst([x["portal"] for x in f["sources"] if not x["enabled"]])}
- Per source: min interval, a **{f["source_max_calls"]}-call** budget per run,
  error tracking, metrics, provenance on every job
- Verified live 2026-09-16: ZipRecruiter (403) and Glassdoor (400) moved to Apify;
  Google Jobs and Monster removed. Evidence: `reports/phase3_source_verification.json`

## Discovery front door — Sector + Job

The user gives a **sector** and a **job**. The USA-wide planner derives the rest:

- Up to **{f["max_title_variants"]}** title variants from the O*NET taxonomy (same
  occupation, shared distinctive word); unknown or vague jobs are searched as typed
- Geography: **nationwide first**; a query that hits a result cap fans out to all
  50 states + DC
- Freshness window: {f["freshness"]}

## Coverage

- Goal is **maximum practical source coverage**, not the first N results. There
  is **no arbitrary global job cap**
- Each source is paged until it is exhausted, refuses, or an explicit NexBase
  budget is reached: **{f["max_pages_per_query"]} pages** and
  **{f["max_results_per_query"]:,} rows** per (source, query)
- **Upstream limits are recorded separately from NexBase limits.** Every
  (source, query) records a stop reason — `SOURCE_EXHAUSTED`,
  `SOURCE_LIMIT_REACHED`, `BLOCKED`, `ROBOTS_RESTRICTED`, `RATE_LIMITED`,
  `ERROR` or `BUDGET_REACHED` — so a source returning nothing is never confused
  with "no such jobs exist"

## Supporting taxonomy

Retained as infrastructure, not as a discovery driver:

- **{f["industries"]}** NAICS 3-digit industries ({f["core_subsectors"]} core / {f["non_core_subsectors"]} non-core)
- **{f["mfg_subsectors"]}** manufacturing sub-sectors
- **{f["search_terms"]:,}** title variants across **{f["soc_codes"]}** SOC codes
- Used for sector dropdowns, search-term suggestions, classification, evidence
  and reporting — never to restrict what a run may search
- Excluded SOC groups: {lst(f["excluded_socs"])}
- No global industry allowlist or exclusion list

## Company evidence resolution

Domain persistence is live via additive `schema.sql` changes (no migrations).

- Persisted provenance on `companies`: `domain`, `domain_confidence`,
  `domain_source`, `domain_evidence_url`, `domain_resolved_at`
- `normalized_domain` remains the **deduplication key** and is never rewritten;
  the verified official domain is stored separately in `domain`
- HIGH/MEDIUM domain cache: **{f["domain_cache_days"]} days**
- LOW/unresolved results: negative-cache TTL **{f["domain_negative_cache_days"]} days**,
  configurable via `domain_negative_cache_days`. Expired results are re-resolved —
  never a permanent verdict
- `DOMAIN_RESOLVER_ENABLED={str(f["domain_resolver"]).lower()}`
- `SIZE_RESOLVER_ENABLED={str(f["size_resolver"]).lower()}` — public-web headcount
  crawling stays implemented and configurable, but is out of the default run
- Unknown company size remains **NEEDS_REVIEW**
- No subdomain persistence; subdomains remain an in-run fallback only

## Rules in force

- Employee size band **{f["size_band"]}**: below or above is rejected, unknown
  goes to NEEDS_REVIEW
- Freshness: {f["freshness"]}
- Never invented: company, domain, posting date, employee count, contact, industry
- Industry evidence states: OBSERVED (source-reported) | INFERRED_HINT (guessed
  from job titles, scores nothing) | UNKNOWN. Only OBSERVED counts as known
- robots.txt checked in the shared access layer, so every self-driven fetch
  inherits it. JobSpy and ats-scrapers use their own clients and are excluded
  from that guarantee
- Every self-driven URL passes an SSRF guard (public http/https addresses only)
- Row level security enabled and forced on all {f["schema_tables"]} tables

## Infrastructure

- Supabase schema: **{f["schema_tables"]} tables**
- Tests: **{f["tests"]} passing**
- Access ladder: Scrapling → Scrapling alt → single-page Camoufox (budgeted)

## Known blockers

The current bottleneck is **company-level qualification evidence, not job
scraping**. Discovery works; proving a company fits the ICP does not.

1. **Employee size unavailable for ~64% of fresh companies** — only Indeed
   publishes headcount; aggregators publish none. A live check read 24 pages
   across 4 resolved domains and found 0 explicit statements. Most rejections
   are missing evidence, not genuine ICP failures.
2. **Domain resolution measured 50%** (4/8 live) and is throttle-sensitive —
   it needs the shared `AccessLayer`.
3. **Industry granularity caps at {f["industries"]}** (BLS crosswalk is 3-digit only).

## Out of scope

Email sending, Instantly, sequences/campaigns, bounce handling, warm-up — to be
planned separately. NexBase stops at export.
"""


def main() -> int:
    check = "--check" in sys.argv
    root = vault_root()
    if root is None or not root.exists():
        print("vault not found; set OBSIDIAN_VAULT to override", file=sys.stderr)
        return 1

    target = root / NOTE
    body = render(facts())

    if target.exists():
        current = target.read_text(encoding="utf-8")
        if MARKER not in current:
            print(f"refusing to overwrite unmanaged file: {target}", file=sys.stderr)
            return 1
        # Ignore the date line so an unchanged build does not churn the note.
        strip = lambda t: re.sub(r"^updated: .*$", "", t, flags=re.M)
        if strip(current) == strip(body):
            print(f"unchanged: {NOTE}")
            return 0

    if check:
        print(f"would update: {NOTE}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(body, encoding="utf-8")
    print(f"synced: {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
